[
    {
        id: 1,
        carID: 1,
        constomer:{
            name: 'John Doe',
            email: 'john.doe@example.com',    
        },
        from: new Date(),
        to: new Date(),
        days: 1,
        daillyRate: 100000,
        total: 100000,
        status: 'active',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        carID: 2,
        constomer:{
            name: 'Jane Doe',
            email: 'jane.doe@example.com',
        },
        from: new Date(),
        to: new Date(),
        days: 1,
        daillyRate: 150000,
        total: 150000,
        status: 'active',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        carID: 3,
        constomer:{
            name: 'Jim Doe',
            email: 'jim.doe@example.com',
        },
        from: new Date(),
        to: new Date(),
        days: 1,
        daillyRate: 200000,
        total: 200000,
        status: 'active',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]